border_width = 2
margin = 0
workspace_margin = 0
default_border_color = "#302D41"
# default_border_color = "#575268"
floating_border_color = "#B5E8E0"
# focused_border_color = "#302D41"
# focused_border_color = "#F28FAD"
# focused_border_color = "#F5C2E7"
focused_border_color = "#E8A2AF"


#F2CDCD
#DDB6F2
#F5C2E7
#E8A2AF
#F28FAD
#F8BD96
#FAE3B0
#ABE9B3
#B5E8E0
#96CDFB
#89DCEB

#161320
#1A1826
#1E1E2E
#302D41
#575268
#6E6C7E
#988BA2
#C3BAC6
#D9E0EE
#C9CBFF
#F5E0DC
