border_width = 2
margin = 5
workspace_margin = 5

default_border_color = "#3B4252"
floating_border_color = "#3B4252"
# focused_border_color = "#3B4252"
# focused_border_color = "#4C566A"
focused_border_color = "#8FBCBB"
# focused_border_color = "#616E88"
# focused_border_color = "#A3BE8C"

#2E3440
#3B4252
#434C5E
#4C566A
#616E88
#D8DEE9
#E5E9F0
#ECEFF4
#8FBCBB
#88C0D0
#81A1C1
#5E81AC
#BF616A
#D08770
#EBCB8B
#A3BE8C
#B48EAD
