modkey = "Mod4"
mousekey = "Mod4"
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]
# tags = ["Kvam", "Folgefonna", "Eidfjord", "Odda", "Fele", "Voss", "Granvin", "Vidda", "Skip"]
# tags = ["Алакритти", "Всемирная Паутина", "Навье-Стокс", "Статья", "Слек", "Сигнал", "7", "8", "9"] #, "Что", "то", "происходит"]

layouts = [
    "MainAndVertStack",
    "MainAndHorizontalStack",
    "MainAndDeck",
    "GridHorizontal",
    "EvenHorizontal",
    "EvenVertical",
    "Fibonacci",
    "LeftMain",
    "CenterMain",
    "CenterMainBalanced",
    "CenterMainFluid",
    "Monocle",
    "RightWiderLeftStack",
    "LeftWiderRightStack",
]

layout_mode = "Tag"
disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true
# max_window_width = 0.7
workspaces = []

window_rules = [
    {window_class = "slack", spawn_on_tag = 5},
    {window_class = "signal", spawn_on_tag = 6},
    # {window_class = "Makie", spawn_on_tag = 4},
    # {window_class = "Makie", focus = false, spawn_floating = true},
    # {window_class = "gksqt", spawn_floating = true},
]

keybind = [
    {command = "SoftReload", modifier = ["modkey", "Shift"], key = "r"},
    {command = "HardReload", modifier = ["modkey", "Control", "Shift"], key = "r"},
    {command = "SwapTags", modifier = ["modkey"], key = "w"},
    {command = "FocusWorkspaceNext", modifier = ["modkey"], key = "l"},
    {command = "FocusWorkspacePrevious", modifier = ["modkey"], key = "h"},
    {command = "FocusWindowUp", modifier = ["modkey"], key = "k"},
    {command = "FocusWindowDown", modifier = ["modkey"], key = "j"},
    {command = "FocusWindowTop", modifier = ["modkey"], key = "m"},
    {command = "MoveWindowUp", modifier = ["modkey", "Shift"], key = "k"},
    {command = "MoveWindowDown", modifier = ["modkey", "Shift"], key = "j"},
    {command = "MoveWindowTop", modifier = ["modkey"], key = "Return"},
    {command = "MoveToLastWorkspace", modifier = ["modkey", "Shift"], key = "w"},
    {command = "MoveWindowToPreviousWorkspace", modifier = ["modkey", "Shift"], key = "h"},
    {command = "MoveWindowToNextWorkspace", modifier = ["modkey", "Shift"], key = "l"},
    {command = "GotoTag", value = "1", modifier = ["modkey"], key = "1"},
    {command = "GotoTag", value = "2", modifier = ["modkey"], key = "2"},
    {command = "GotoTag", value = "3", modifier = ["modkey"], key = "3"},
    {command = "GotoTag", value = "4", modifier = ["modkey"], key = "4"},
    {command = "GotoTag", value = "5", modifier = ["modkey"], key = "5"},
    {command = "GotoTag", value = "6", modifier = ["modkey"], key = "6"},
    {command = "GotoTag", value = "7", modifier = ["modkey"], key = "7"},
    {command = "GotoTag", value = "8", modifier = ["modkey"], key = "8"},
    {command = "GotoTag", value = "9", modifier = ["modkey"], key = "9"},
    {command = "GotoTag", value = "10", modifier = ["modkey"], key = "0"},
    {command = "MoveToTag", value = "1", modifier = ["modkey", "Shift"], key = "1"},
    {command = "MoveToTag", value = "2", modifier = ["modkey", "Shift"], key = "2"},
    {command = "MoveToTag", value = "3", modifier = ["modkey", "Shift"], key = "3"},
    {command = "MoveToTag", value = "4", modifier = ["modkey", "Shift"], key = "4"},
    {command = "MoveToTag", value = "5", modifier = ["modkey", "Shift"], key = "5"},
    {command = "MoveToTag", value = "6", modifier = ["modkey", "Shift"], key = "6"},
    {command = "MoveToTag", value = "7", modifier = ["modkey", "Shift"], key = "7"},
    {command = "MoveToTag", value = "8", modifier = ["modkey", "Shift"], key = "8"},
    {command = "MoveToTag", value = "9", modifier = ["modkey", "Shift"], key = "9"},
    {command = "MoveToTag", value = "10", modifier = ["modkey", "Shift"], key = "0"},
    {command = "IncreaseMainWidth", value = "5", modifier = ["modkey"], key = "x"},
    {command = "DecreaseMainWidth", value = "5", modifier = ["modkey", "Shift"], key = "x"},
    {command = "NextLayout", modifier = ["modkey", "Control"], key = "k"},
    {command = "PreviousLayout", modifier = ["modkey", "Control"], key = "j"},
    {command = "ToggleSticky", modifier = ["modkey"], key = "y"},
    {command = "ToggleFloating", modifier = ["modkey", "Shift"], key = "space"},
    {command = "CloseWindow", modifier = ["modkey", "Shift"], key = "c"},
    {command = "ToggleScratchPad", value = "Vimb", modifier = ["modkey"], key = "v"},
    # {command = "ToggleScratchPad", value = "Qutebrowser", modifier = ["modkey"], key = "q"},
    {command = "ToggleScratchPad", value = "alacritty", modifier = ["modkey", "Shift"], key = "a"},
    {command = "ToggleScratchPad", value = "htop", modifier = ["modkey"], key = "z"},
    {command = "ToggleScratchPad", value = "tty-clock", modifier = ["modkey"], key = "c"},
    {command = "Execute", value = "/home/syver/.local/bin/hardanger", modifier = ["modkey"], key = "r"},
    {command = "Execute", value = "wezterm start /home/syver/.local/bin/dot", modifier = ["modkey", "Shift"], key = "d"},
    {command = "Execute", value = "/home/syver/.local/bin/screenlayout", modifier = ["modkey", "Shift"], key = "n"},
    {command = "Execute", value = "rofi -show run", modifier = ["modkey"], key = "p"},
    # {command = "Execute", value = "/home/syver/.local/bin/run_dmenu_run", modifier = ["modkey"], key = "p"},
    {command = "Execute", value = "/home/syver/.local/bin/run_clipmenu", modifier = ["modkey"], key = "i"},
    {command = "Execute", value = "/home/syver/.local/bin/keyboardmenu", modifier = ["modkey"], key = "g"},
    {command = "Execute", value = "setxkbmap us",                       modifier = ["modkey", "Control"], key = "1"},
    {command = "Execute", value = "setxkbmap no",                       modifier = ["modkey", "Control"], key = "2"},
    {command = "Execute", value = "setxkbmap fr",                       modifier = ["modkey", "Control"], key = "3"},
    {command = "Execute", value = "setxkbmap ru",                       modifier = ["modkey", "Control"], key = "4"},
    {command = "Execute", value = "setxkbmap -layout us -variant intl", modifier = ["modkey", "Control"], key = "5"},
    {command = "Execute", value = "setxkbmap us",                       modifier = ["modkey", "Control"], key = "ampersand"},
    {command = "Execute", value = "setxkbmap no",                       modifier = ["modkey", "Control"], key = "eacute"},
    {command = "Execute", value = "setxkbmap fr",                       modifier = ["modkey", "Control"], key = "quotedbl"},
    {command = "Execute", value = "setxkbmap ru",                       modifier = ["modkey", "Control"], key = "apostrophe"},
    {command = "Execute", value = "setxkbmap -layout us -variant intl", modifier = ["modkey", "Control"], key = "parenleft"},
    {command = "Execute", value = "emacs", modifier = ["modkey", "Shift"], key = "e"},
    {command = "Execute", value = "flameshot gui", modifier = ["modkey", "Shift"], key = "i"},
    {command = "Execute", value = "flameshot screen -c", modifier = [], key = "Print"},
    {command = "Execute", value = "kitty", modifier = ["modkey", "Control", "Shift"], key = "Return"},
    {command = "Execute", value = "wezterm", modifier = ["modkey", "Shift"], key = "Return"},
    {command = "Execute", value = "WINIT_X11_SCALE_FACTOR=1 alacritty", modifier = ["modkey", "Control"], key = "Return"},
    {command = "Execute", value = "brave", modifier = ["modkey", "Shift"], key = "b"},
    {command = "Execute", value = "firefox", modifier = ["modkey", "Control", "Shift"], key = "f"},
    {command = "Execute", value = "vimb", modifier = ["modkey", "Shift"], key = "v"},
    {command = "Execute", value = "qutebrowser", modifier = ["modkey", "Shift"], key = "q"},
    {command = "Execute", value = "luakit", modifier = ["modkey", "Shift"], key = "u"},
    {command = "Execute", value = "zathura", modifier = ["modkey", "Shift"], key = "z"},
    {command = "Execute", value = "wezterm start ranger", modifier = ["modkey"], key = "f"},
    {command = "Execute", value = "pcmanfm", modifier = ["modkey", "Shift"], key = "f"},
    {command = "Execute", value = "rofi -show emoji -modi emoji", modifier = ["modkey", "Control", "Shift"], key = "e"},
    # {command = "Execute", value = "slock", modifier = ["modkey", "Control"], key = "l"},
    {command = "Execute", value = "light-locker-command -l", modifier = ["modkey", "Control"], key = "l"},
    {command = "Execute", value = "dunstctl close", modifier = ["modkey"], key = "comma"},
    {command = "Execute", value = "dunstctl close-all", modifier = ["modkey", "Shift"], key = "comma"},
    {command = "Execute", value = "dunstctl history-pop", modifier = ["modkey"], key = "period"},
    {command = "Execute", value = "dunstctl context", modifier = ["modkey", "Shift"], key = "period"},
    {command = "Execute", value = "/home/syver/.local/bin/bgrand", modifier = ["modkey"], key = "b"},
    {command = "Execute", value = "/home/syver/.local/bin/setbgdir", modifier = ["modkey", "Control"], key = "b"},
    {command = "Execute", value = "/home/syver/projects/instant-reference/copy-reference.js", modifier = ["modkey", "Shift"], key = "o"},
    {command = "Execute", value = "/home/syver/.local/bin/article", modifier = ["modkey", "Shift"], key = "p"},
]

[[scratchpad]]
name = "Vimb"
value = "vimb"
x = 0.2
y = 0.1
height = 0.8
width = 0.6

# [[scratchpad]]
# name = "Qutebrowser"
# value = "qutebrowser google.com --target window"
# x = 0.2
# y = 0.1
# height = 0.8
# width = 0.6

[[scratchpad]]
name = "alacritty"
value = "WINIT_X11_SCALE_FACTOR=1 alacritty"
x = 0.3
y = 0.25
height = 0.5
width = 0.4

[[scratchpad]]
name = "htop"
# value = "wezterm start htop"
value = "WINIT_X11_SCALE_FACTOR=1 alacritty -e htop"
x = 0.2
y = 0.15
height = 0.7
width = 0.6

[[scratchpad]]
name = "tty-clock"
# value = "wezterm start htop"
value = "WINIT_X11_SCALE_FACTOR=1 alacritty -e tty-clock -cs"
x = 0.35
y = 0.4
height = 0.2
width = 0.25

# AZERTY
# &	ampersand
# é	eacute
# "	quotedbl
# '	apostrophe
# (	parenleft
# è	egrave
# _	underscore
# ç	ccedilla
# à	agrave
