#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise # off, autoraise, autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               off

# Yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                off
yabai -m config window_border_width          20
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# General space settings
yabai -m config layout                       bsp # stack, bsp, float
yabai -m config top_padding                  00
yabai -m config bottom_padding               00
yabai -m config left_padding                 00
yabai -m config right_padding                00
yabai -m config window_gap                   05

# Rules
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Systeemvoorkeuren$' manage=off
yabai -m rule --add title='Figure *' manage=off
yabai -m rule --add title='FaceTime' manage=off

echo "yabai configuration loaded.."
