# Dracula
[colors]
foreground = "#f8f8f2"
background = "#282a36"
cursor_bg = "#f8f8f2"
cursor_border = "#abb2bf"
cursor_fg = "#282a36"
selection_bg = "#44475a"
selection_fg = "#ffffff"

ansi    = [ "#282a36", "#ff5555", "#50fa7b", "#f1fa8c", "#caa9fa", "#ff79c6", "#8be9fd", "#bfbfbf" ]
brights = [ "#575b70", "#ff6e67", "#5af78e", "#f4f99d", "#caa9fa", "#ff92d0", "#9aedfe", "#e6e6e6" ]
