# One Dark
[colors]
foreground = "#abb2bf"
background = "#282c34"
cursor_bg = "#abb2bf"
cursor_border = "#abb2bf"
cursor_fg = "#282c34"
selection_bg = "#4b5263"
selection_fg = "#ffffff"

ansi    = [ "#282c34", "#be5046", "#98c379", "#d19a66", "#61afef", "#c678dd", "#56b6c2", "#abb2bf" ]
brights = [ "#5c6370", "#e06c75", "#98c379", "#e5c07b", "#61afef", "#c678dd", "#56b6c2", "#ffffff" ]
