#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

leftwm-command UnloadTheme

pkill unclutter
pkill picom 
pkill polybar
pkill dunst
pkill lxsession
pkill conky
pkill clipmenud
