#!/bin/bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

unclutter --timeout 1 --ignore-scrolling &
picom --experimental-backends &> /dev/null &
dunst &
# conky &

clipmenud &

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
nitrogen --restore

# Boot a polybar for each monitor
polybar -m | sed s/:.*// | tac | while read -r monitor
do
    monitor=$monitor polybar main &> /dev/null &
    # if [ "$monitor" == "DP3" ]; then
    #     monitor=$monitor polybar smallbar &> /dev/null &
    # else
    #     monitor=$monitor polybar main &> /dev/null &
    # fi
done
